import { NotExistPage } from '../components/page/not-exist/not-exist-page.component.tsx'
import {TRoute} from '../shared-react-components/AlexRouter/AlexRouter.tsx'
import {MapPage} from '../components/page/map/map-page.component.tsx'
import {PlacePage} from '../components/page/place/place.component.tsx'


export const routesListConfig: TRoute[] = [
    {
        path: '/',
        name: 'Главная',
        component: "DUDE WHAT THE HELL",
    },

    {
        path: '/service',
        name: 'Сервисы',
        component: "DUDE WHAT THE HELL",
    },

    {
        path: '/map',
        name: 'Маршруты',
        component: <MapPage/>,
    },

    {
        path: '/places/place',
        name: 'Место',
        component: <PlacePage/>,
    },

    {
        path: '/favourite',
        name: 'Избранное',
        component: "DUDE WHAT THE HELL",
    },

    {
        path: '*',
        name: 'Не существует',
        component: <NotExistPage/>,
    },
]

const mapRoutesListPaths = (routesList: TRoute[]): string[] => {
    const resultArr: string[] = []

    routesList.map((item) => {
        resultArr.push(item.path)
        if (item.routes) {
            resultArr.push(...mapRoutesListPaths(item.routes))
        }
    })

    return resultArr
}

const mapRoutesListNames = (routesList: TRoute[]): [string, string][] => {
    const resultArr: [string, string][] = []

    routesList.map((item) => {
        resultArr.push([item.path, item.name])
        if (item.routes) {
            resultArr.push(...mapRoutesListNames(item.routes))
        }
    })

    return resultArr
}
export const autoGeneratedRoutesListMap = new Map(mapRoutesListNames(routesListConfig))
export const autoGeneratedAllowedLinks = mapRoutesListPaths(routesListConfig)